baseURL = "https://www.hanifsgy.com/"
languageCode = "en-us"
title = "SGY"
theme = "hugo-theme-slim"
Paginate = 5
enableEmoji = true

[params]
  Subtitle = "Weekly Note Taking iOS Swift"
  #GithubID = "hanifsgy"
  #TwitterID = "hanif_sgy"
  #AnalyticsID = "Your Google Analytics tracking code"
  #DisqusShortname = "Your Disqus shortname"
  Summary = true  # takes true or false
  Content = true  # takes true or false
  # if both are set to true, summary is shown.
  FooterMsg = "Powered by Hugo."

[Author]
  name = "Hanif Sugiyanto"
  email = "hanifsgy@gmail.com"
  github = "hanifsgy"
  twitter = "hanif_sgy"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2

[[menu.main]]
    name = "About me / contact"
    url = "/about/"
    weight = 3
